import Head from "next/head";
import { useState } from "react";
import { ActionButton } from "../components/ActionButton";
import { DraftStorage } from "../components/DraftStorage";

export default function Home() {
  const [textBoxValue, setTextBoxValue] = useState("");

  const [isClicked, setIsClicked] = useState(false);

  const [draftSwitch, setDraftSwitch] = useState(false);

  const [draftStorage, setDraftStorage] = useState([]);

  const handleInputChange = (event) => {
    setTextBoxValue(event.target.value);
  };
  const handleSubmit = () => {
    if (textBoxValue === "") {
      console.log("テキストボックスは空です");
    } else {
      alert(textBoxValue);
    }
  };

  const handelClickCancel = () => {
    if (textBoxValue) {
      setIsClicked(!isClicked);
    }
  };

  const draftOpen = () => {
    setDraftSwitch(!draftSwitch);
  };
  //下書きを押したときに下からスライドして下書きを表示させる

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen overflow-hidden box-border">
        <div
          className={`bg-black opacity-50 h-screen relative z-20 ${
            isClicked ? "" : "hidden"
          }`}
        ></div>
        <div className="mx-5">
          <ul className="grid grid-cols-5 fixed w-full top-5">
            <li className="col-span-3">
              <button onClick={handelClickCancel}>キャンセル</button>
            </li>
            <li className={`${draftStorage.length === 0 ? "hidden" : ""}`}>
              <button onClick={draftOpen}>下書き</button>
            </li>
            <li className={`${draftStorage.length === 0 ? "" : "hidden"}`}></li>
            <li>
              <button onClick={handleSubmit}>投稿する</button>
            </li>

            <div>
              <textarea
                type="text"
                placeholder="投稿したい内容"
                value={textBoxValue}
                onChange={handleInputChange}
                className="mt-5 outline-none w-screen"
              />
            </div>
          </ul>
        </div>
        <ActionButton
          isClicked={isClicked}
          handelClickCancel={handelClickCancel}
          textBoxValue={textBoxValue}
          setTextBoxValue={setTextBoxValue}
          draftStorage={draftStorage}
          setDraftStorage={setDraftStorage}
        />

        <DraftStorage draftSwitch={draftSwitch} draftStorage={draftStorage} />
      </div>
    </div>
  );
}
